// Automatisch gegenereerd uit klaverjas/KJKRT.C - niet met de hand aanpassen.
// Bron: de tekenroutines aas(), heer(), vrouw(), boer() en kleuren().
// Elk teken is een pixel; de kleurtabel per plaatkaart komt uit de switch
// in de bijbehorende C-functie. Kleur -1 betekent "GREEN + kleurnummer",
// waardoor die pixels per kaartkleur verschillen, precies als in het origineel.

namespace Klaverjas.Ui;

internal static class KaartData
{
    public static readonly string[] Aas =
    {
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccaaaaaaacccccccccccccccccccccc",
        "cccccccccccccccccccccaaaaaaaaaaccccccccccccccccccc",
        "ccccccccccccccccccccaaaaaaaaaaaaaccccccccccccccccc",
        "cccccccccccccccccccaaaaaaaaaaacccccccccccccccccccc",
        "cccccccccccccccccccyyyyyyyyyyycccccccccccccccccccc",
        "cccccccaaaaacccccccyyyyyyyyyyccccaaaaaaccccccccccc",
        "ccccccaaaaaaaccccccccccccccccccaaaaaaaaaaaaacccccc",
        "ccccccaaaaaaaaccccccccccRccccccaaaaaaaaaaaaccccccc",
        "cccccyyyyyyyyyccccccccccRRcccccyyyyyyyyyaccccccccc",
        "ccccccyyyyyyyccccccccccRrRcccccyyyyyyyyccccccccccc",
        "ccccccyyyyyycccccccccccRrRcccccyyyyyyycccccccccccc",
        "cccccccccccccccccccccccRrrRccccccccccccccccccccccc",
        "ccccccccccccccccccccccRrrrRccccccccccccccccccccccc",
        "ccccccccccccccccccccccRrrrRccccccccccccccccccccccc",
        "ccccccRccccccccccccccRrrrrrRcccccccccccccccccccccc",
        "ccccccRRcRccccccccccRrruuurrRccccccccccccccccccccc",
        "cccccRrrzrRccccccccczYYyyyYYzccccccccccccccccccccc",
        "ccccRrrrzrRccccccccczyzuuuzuzccccccRcccccccccccccc",
        "cccczzzzzzzRRRRRcccczuuuuuuuzcccccRzRcccRccccccccc",
        "cccczeuuzuzrrrzRRRRRzeuzzzuuzccccRrzrRcRRccccccccc",
        "cccczeuuzezrrrrzrrrrzzzeuuzzzcccRrrzrRRrrRcccccccc",
        "cccczeuuzuzrrrrzrrrrzeeeuuuuzccRrrzzzRRrrrRccccccc",
        "cccczeeuzezrrrrrzrrrzeeeuuuuzcczzzuuzzzzzrRccccccc",
        "cccczeuuzuzrrrrrzrrrzeeeuuuuzcczeeuuzuzeezzccccccc",
        "cccczeuuzuzrrrrrrzrrzeeuuuuuzzczeeuuzuzuuuzccccccc",
        "cccczezzzzzzzzzzzzzzzeeuuuuuzuzzeeuuzuzuuuzccccccc",
        "cggczuzuzuzuzuzuzuzuzeuuuuuuzuuuzeuuzuzuuuzccccccc",
        "ggggzuzeuuuuuzzzzzzzzeuuuuuuzuuuzuuuzuzuuuzccccccc",
        "ggggzuzzzzzzzzuuuuuuzeuuuuuuzuuuzuuuzuzuuuzccccccc",
        "ggggzuzeeuguuguuuuuuzeuuuuuuzuuuzuuuzuzuuuziiiiiii",
        "gzgizuzeeuguuguuuuuuzuuuuuuuzuuuzuuuzuzuuuziiiiiii",
        "iziizuzeuugzggguuuuuzeeuuuuuzuuuzuuuzuzuuuzzzzzzzz",
        "iziizuzeuuuzuuuuuuuuzeuuuuuuzuuuzuuuzuzuubbuuuubbz",
        "iziizuzeguuzuuguuuugzeeuuuuuzuuuzUUUzbzUUbbuuuubbz",
        "iziizuzeguuzuggguuggzuuuuuuuzuuggbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbggggggggzuuuuuuuzggbbbbbbbbbbbbbbbbbbb",
        "wwwwwwwbbbbbbbbbbbbbzUUUUUUUzbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbwwwwwgbbbbbbbbbbbbwwwggbbbbbbbbbbbbbbb",
        "bbbbbbggwbbbbbbbbbbwwwwwwggbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbggbbbbbbbbbbbbbbbbbggbbbwwwwwwggbbbbbbbbbbbb",
        "bbbbbbbbbbbbbggbwwwwwwwbbbbbbbbbbbbbggbbbbbbbbbbbb",
        "bbbbbbbbbbbbbggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbgbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbgiiiiiiiiiiiiiiiibbbbbbbbbiiii",
        "bbbbiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    };

    public static readonly (char Teken, int Kleur)[] AasPalet =
    {
        ('a', 7),
        ('b', 1),
        ('c', 9),
        ('e', 14),
        ('g', 2),
        ('i', 10),
        ('j', 12),
        ('n', 11),
        ('o', 3),
        ('p', 5),
        ('r', -1),
        ('t', 13),
        ('u', 6),
        ('w', 15),
        ('y', 8),
        ('z', 0),
    };

    public static readonly string[] Heer =
    {
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxzzzzzzzzzzzzxxxxxxxxxxjxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEegeegeegeeExxxxxxxxxjjjjxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEEEEEEEEEEEExxxxxxxxjjjjjjxxxxxx",
        "xxxxxxxxxxxxxxxxxxrrrwwwwwwwwwxxxxxxxxxjjjjxxxxxxx",
        "xxxxxxxxxxxxxxxxxxrrrwwwwwwwwwrxxxxxxxxxjjxxxxxxxx",
        "xxxxxxxxxxxxxxxxxrrrrrwzzwwzzrrxxxxxxxxEEEExxxxxxx",
        "xxxxxxxxxxxxxxxxrrrrrwwwwzwwwrrxxxxxxxEeeExxxxxxxx",
        "xxxxxxxxxxxxxxxxrrrrwwwwwwzwwrrxxxxxxxEbeExxxxxxxx",
        "xxxxxxxxxxxxxxxrrrrrwwwwwwzwwrrxxxxxxEeeExxxxxxxxx",
        "xxxxxxxxxxxxxxxrrrrrwwwwwzzwwrrxxxxxxEjjExxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrwwwwwwwwwrrxxxxxEjjExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrzrrrzrrrxxxxxEeeExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrzzrrrrxxxxxEeeExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrrrrrwrxxxxEegExxxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrrrrrwrxxxxEeeExxxxxxxxxxx",
        "xxxxxxxxxxxxxxrErrPrrrrrrrrrrPrxxxxEbeExxxxxxxxxxx",
        "xxxxxxxxxxxxxxEeePppppprrrrrrpppPxEeeExxxxxxxxxxxx",
        "xxxxxxxxxxxxxEeeePppppppprrrpppPeEppExxxxxxxxxxxxx",
        "xxxxxxxxxxxBbEeeeePpppppppppppPeeEppExxxxxxxxxxxxx",
        "xxxxxxxxxxBbbbbEeeeePPPPppppEEeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxxBbbbbbEEeeeeeeeEEEEeeeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbEeeeeeeeeeeeeeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbbEEeeeeeeeeeeeEeeEBxxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbbbbbEEEEEEEEbEeeEbbBxxxxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbbbbbbbbEeeEbbbbBxxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbbGbbbbbErrEbbbbbBxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbGgGGbbErrEbbbbbbBxxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbbGggggGbEeeEbbbbbbbBxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbbGgggggEttEbbbbbbbbBxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbGgpppggEetEbbbbbbbbbBxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbGzzpppzEeeEbbbbbbbbbbBxxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbbGggpppgEeeEgBbbbbbbbbbBxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGgggggggEezEgBbbbbbbbbbBxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGggggggEieEgggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGggggggEiiEgggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbGggggggEeeEggggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbGggggggEooEggggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbGgggggggEooEgggggBbbbbbbbbbBxxxxx",
        "xxxxxBbbbbbbbbbbbGggggggEeeEggggggBbbbbbbbbbBxxxxx",
        "xxxxxBbbbbbbbbbbGgtttgggEeeEggggttBbbbbbbbbbBxxxxx",
        "xxxxBbbbbbbbbbbGgttgttgEeuEggggttgtBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbbGgttgggttEuuEgggttgggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbbGttgggggEeeEgggttggggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbGttggggggEeeEggttgggggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbGtgggggggEeetgttggggggBbbbbbbbbbBxxxx",
    };

    public static readonly (char Teken, int Kleur)[] HeerPalet =
    {
        ('a', 7),
        ('b', 1),
        ('c', 9),
        ('e', 14),
        ('g', 2),
        ('i', 10),
        ('j', 12),
        ('o', 3),
        ('p', 5),
        ('r', -1),
        ('t', 11),
        ('u', 6),
        ('w', 15),
        ('x', 13),
        ('y', 8),
        ('z', 0),
    };

    public static readonly string[] Vrouw =
    {
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaiijjiijjiijaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaiijjiijjiijaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEEEEEEEEEEEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEeeettteeeEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEeettttteeEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaazzzzzzzzzzzaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaRrrrrrrrrrrrRaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzrrrrrrrrrrRaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzrrrrrrrrrrrRaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzwwwwwwwwrrrPPPaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrwwwwwwwwwrrrPppPaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaRrwwwwwzzwwwrPppppPaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaZwzzwwzzwwwrrPppPcaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaZwzzwzwwwwwwrPPPccaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaZwwwzwwwwwwwZcccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaZwwwzzwwwwwwZcccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaZwwwwwzwwwZccccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaZwzzzwwwzZcccccccaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwzwZcccccccaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZzzzzwwwwZcccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwZcccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwwZccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwwZcccccccaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaBZZZwwwwwwwwwwZccccccaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaBbBwwwwwwwwwwwBbBccccccaaaaaaaaaa",
        "aaaaaaaaaaaIZZZZZZBbbbBwwwwwwBbbbbEEccccaaaaaaaaaa",
        "aaaaaaaaaIiiiIaWWWwwBbbBBBBBBbbbbEeeeEccaaaaaaaaaa",
        "aaaaaaaaIIiiIwwwwwwwBbbbbbbbbbbbEeeeeeEcaaaaaaaaaa",
        "aaaaaaaaIiiiiIwwwwwwwwwBBBBBwwwEeeeeeeEaaaaaaaaaaa",
        "aaaaaaaaIiiiiiIwwwwwwwwwwwwwwwEEeeeeeeeEaaaaaaaaaa",
        "aaaaaaaIiiiiiiIwwwwwwzwwwwwwwwEeeeeeeeeEEaaaaaaaaa",
        "aaaaaaaIiiiiiiiIwwwwzwwwwwwwIEeeeeeeeeeeEaaaaaaaaa",
        "aaaaaaIiiiiiiiiIwwwzwwwwwwIiEeeeeeeeeeeeIaaaaaaaaa",
        "aaaaaaIiiiiiiiiiIwwzwwwwIiiEeeeeeeeeeeIiIaaaaaaaaa",
        "aaaaaaIiiiiiiiiiIwzwwwIiiiiEeeeeeeeeIiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiIzwIiiiiiiEeeeeeeeIiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiIIiiiiiiEeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiiieeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiiEeeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiIaaaaaaaaa",
        "aaaaUuiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiiUaaaaaaaaa",
        "aaaaUuuiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiUuUaaaaaaaaa",
        "aaaaUuuuiiiiiiiiiiiiiEeeeeeeeEiiiijjjUuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjiiiiiiEeeeeeeeEjjjjjjjUuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjjjjjjEeeeeeeeEjjjjjjjUuuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjjjjjjEeeeeeeeEjjjjjiUuuuuUaaaaaaaaa",
        "aaaUuuuuiiiiijjjjjjEeeeeeeeEiiiiiiUuuuuuUaaaaaaaaa",
    };

    public static readonly (char Teken, int Kleur)[] VrouwPalet =
    {
        ('a', 7),
        ('b', 1),
        ('c', 9),
        ('e', 14),
        ('g', 2),
        ('i', 10),
        ('j', 12),
        ('o', 3),
        ('p', 5),
        ('r', -1),
        ('t', 11),
        ('u', 6),
        ('w', 15),
        ('x', 13),
        ('y', 8),
        ('z', 0),
    };

    public static readonly string[] Boer =
    {
        "ccccccccccccccccccccccccccccJJJJJccccccccccccccccc",
        "ccccccccccccccccccccccccccJJjjjjJccccccccccccccccc",
        "cccccccccccccccccccccccccJjjjjjJcccccccccccccccccc",
        "ccccccccccccccccccccccccJjjjjjJccccccccccccccccccc",
        "cccccccccccccccccccccccJjjjjjJcccccccccccccccccccc",
        "cccccwwwwwwwwwwwwwccccJjjjjJJccccccccccccccccccccc",
        "ccccwwwwwwwwwwwwwwwwpJjjjJJcccccccccwwwwwccccccccc",
        "ccccccwwwwwwwwwwwwpPJjjJJPPccccccccwwwwwwwcccccccc",
        "ccccwwwwwwwwwwwwwwwPJjJppppPPccccccccccccccccccccc",
        "ccwwwwwwwwwwwwwwcccPJJpppppppPPPcccccccccccccccccc",
        "cwwwwwwwwwwwwwcccPPpppppppppppppPPPcccccgggggggccc",
        "cwwwwwwwwwwwwwcccPppppppppppppppppPccgggggggjjgggc",
        "cyyyyyyyyyyyyyccccPPPPPPPPPPpppppPPccgggjjggjjggjj",
        "cyyyyyyyyyyyyycccccRrrrWwwwPPPPPPcccggggjjggggggjj",
        "cccccccYcccccccccccRrrWwwwwwwwrrRcccggggggjjggjjgg",
        "cccccccYYcccccccccRrrWwZZwwZZwWrRccggjjgggjjggjjgg",
        "cccccccYyYccccccccRrWwwwwZwwwwWrRcccgjjggjjggggggg",
        "cccccccYyyYYccccccRrWwwwwZwwwwWrRcccgggggjjggggjjg",
        "cccccccYyyYyYcccccRrWwwwwZwwwwWrRcccccgggggjjggjjg",
        "ccccccccYyYYyYccccRrrWwWrrrrwwWrRcccccccgggjjggggg",
        "ccccccccYyYUYyYcccRrrrWWrrrrwwWrRccccccccccuuuuccc",
        "ccccccccYyYUUYyYccRRRRwwZZZZWWRRRccccccccccuuuuccc",
        "ccccccccYyYUuUYyYccccccZrrrrwzwRcccccccccccuuuuccc",
        "ccccccccYyYcUuUYYYccccZWrrrrzwwZcccccccccccuuuuccc",
        "cccccccccYYcUuUccYYcccZwrrrrwwwwZccccccccccuuuuccc",
        "cccccccccYcccUuUcccYcZWwwwwwwwwwZccccccccccuuuuccc",
        "cccccccccYcccUuUcccccZWWWWWWWWWWWZEEEccccccuuuuccc",
        "ccccccccccccccUuUccjjjjwwwjeeeeeeeeeeEcccccuuuuccc",
        "cccccccccccccccUuUjjjjjjjjEeeeeeeeeeeeEccccuuuuccc",
        "ccccccccccGGGGGUuUbbbjjjjEeeeeeeeeeeeeeEcccuuuuccc",
        "ccccccccGGggggggUuUbbbbbbEeeeeeeeeeeeeeEcccuuuuccc",
        "cccccccGgggggggugUuUbbbbEeeeeeeeeeeeeeeEEccuuuuccc",
        "cccccccGgggggggggUuUbbbEeeeeeeeeeeeeEEEggGcuuuuccc",
        "ccccccGggggggggBbBUuUbEeeeeeeeeeeeeEgggggGcuuuuccc",
        "ccccccGgggggggBbbbUuUeEeeeeeeeeeeEgggggggGcuuuuccc",
        "cccccGgggggggBbbbbbUuUeeeeeeeeeeEgggggggggGuuuuccc",
        "cccccGgggggggBbbbbgUuUeeeeeeeeeEggggggggggGuuuuccc",
        "cccccGgggggggBbbbbbbUuUeeeeeeeeEgggggggggggGuuuccc",
        "cccccGgggggggBbbbbbbUuUeeeeeeeEbbbGgggggggggGuuccc",
        "iiiiiGgggggggBbbbbbEeUuUeeeeeEbbbbBGgggggggggGuiii",
        "iiiiiGgggggggBbbbbEeeUuUeeeeeEbbbbBGggggggggggGiii",
        "iiiiiGgggggggBbbbEeeeeUuUeeeeEbbbbBiGgggggggggGiii",
        "iiiiGgggggggBbbbbEeeeeUuUeeeEbbbbbBiiGggggggggGiii",
        "iiiiGgggggggBbbbEeeeeeeUuUeeEbbbbBiiiGgggggggGiiii",
        "iiiiGgggggggBbbbEeeeeeeUuUeebbbbbBiiGggggggggGiiii",
        "iiiiGgggggggBbbEeeeeeeeeUuUeebbbbBiiGgggggggGiiiii",
        "iiiiGgggggggBbbEeeeeeeeeeUuUebbbbBiiGggggggGiiiiii",
        "iiiiGgggggggBbbEeeeeeeeeEUuUebbbbBiGggggggGiiiiiii",
        "iiiiGgggggggBBeeeeeeeeeeEbUuUbbbbBGgggggggGiiiiiii",
    };

    public static readonly (char Teken, int Kleur)[] BoerPalet =
    {
        ('a', 7),
        ('b', 1),
        ('c', 9),
        ('e', 14),
        ('g', 2),
        ('i', 10),
        ('j', 12),
        ('o', 3),
        ('p', 5),
        ('r', -1),
        ('t', 11),
        ('u', 6),
        ('w', 15),
        ('x', 13),
        ('y', 8),
        ('z', 0),
    };

    public static readonly string[] Klaver =
    {
        "wwwwwzzzwwwwww",
        "wwwwzzzzzwwwww",
        "wwwwzzzzzwwwww",
        "wwwwwzzzwwwwww",
        "wzzwwwzwwwzzww",
        "zzzzzwzwzzzzzw",
        "zzzzzzzzzzzzzw",
        "zzzzzwzwzzzzzw",
        "wzzwwwzwwwzzww",
        "wwwwwwzwwwwwww",
        "wwwwwzzzwwwwww",
        "wwwwwzzzwwwwww",
        "wwwwzzzzzwwwww",
        "wwwwwwwwwwwwww",
    };

    public static readonly string[] Schoppen =
    {
        "wwwwwwZwwwwwww",
        "wwwwwZZZwwwwww",
        "wwwwZZZZZwwwww",
        "wwZZZZZZZZZwww",
        "wZZZZZZZZZZZww",
        "ZZZZZZZZZZZZZw",
        "ZZZZZZZZZZZZZw",
        "ZZZZZZZZZZZZZw",
        "wZZZZwZwZZZZww",
        "wwZZwZZZwZZwww",
        "wwwwwwZwwwwwww",
        "wwwwwZZZwwwwww",
        "wwwwZZZZZwwwww",
        "wwwZZZZZZZwwww",
    };

    public static readonly string[] Ruiten =
    {
        "wwwwwwrwwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwrrrrrwwwww",
        "wwwrrrrrrrwwww",
        "wrrrrrrrrrrrww",
        "rrrrrrrrrrrrrw",
        "wrrrrrrrrrrrww",
        "wwwrrrrrrrwwww",
        "wwwwrrrrrwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwwrwwwwwww",
        "wwwwwwwwwwwwww",
    };

    public static readonly string[] Harten =
    {
        "wwRRRwwwRRRwww",
        "wRRRRRwRRRRRww",
        "RRRRRRwRRRRRRw",
        "RRRRRRRRRRRRRw",
        "wRRRRRRRRRRRww",
        "wRRRRRRRRRRRww",
        "wwRRRRRRRRRwww",
        "wwwRRRRRRRwwww",
        "wwwwRRRRRwwwww",
        "wwwwRRRRRwwwww",
        "wwwwwRRRwwwwww",
        "wwwwwRRRwwwwww",
        "wwwwwwRwwwwwww",
        "wwwwwwwwwwwwww",
    };

    public static string[] Plaat(char rang) => rang switch
    {
        'A' => Aas,
        'H' => Heer,
        'V' => Vrouw,
        'B' => Boer,
        _ => null
    };

    public static (char, int)[] Palet(char rang) => rang switch
    {
        'A' => AasPalet,
        'H' => HeerPalet,
        'V' => VrouwPalet,
        'B' => BoerPalet,
        _ => null
    };

    public static string[] Symbool(int kleur) => kleur switch
    {
        0 => Klaver,
        1 => Schoppen,
        2 => Ruiten,
        _ => Harten
    };
}
